CONSTANT_KEY = {
    # APPOINMENT_STATUS
      "APPOINTMENT_STATUS_PENDING_PAYMENT" : "0" #
    , "APPOINTMENT_STATUS_ACTIVE" : "1" #Done
    , "APPOINTMENT_STATUS_CHECKED" : "2" # R-View D- Active View
    , "APPOINTMENT_STATUS_ON_WAY": "3"  # Checked Edit
    , "APPOINTMENT_STATUS_BOOKED" : "4" # edit onway
    , "APPOINTMENT_STATUS_FOLLOW" : "5" # confirm
    , "APPOINTMENT_STATUS_DONE" : "6" # view
    , "APPOINTMENT_STATUS_PAID" : "7" # view

    # ROLE
    , "ROLE_MANAGER": "0"
    , "ROLE_DOCTOR": "1"
    , "ROLE_RECEPTION" : "2"
    , "ROLE_DOCTOR_MASTER": "3"

    #DELETE_FLAG
    , "DELETE_FLAG_FALSE": "0"
    , "DELETE_FLAG_TRUE": "1"

    #TREATMENT_FLAG
    , "TREATMENT_STATUS_DONE": "0"
    , "TREATMENT_STATUS_PLAN": "1"
}



